controllers:
    resource: ../../src/Controller/**/*
    exclude: ../../src/Controller/Admin
    type: attribute

admin:
    resource: ../../src/Controller/Admin/
    type: attribute
    prefix: '/Admin'
    # name_prefix: 'admin_'
